### ISSUE TITLE
Problem with "get-vaultdomain" command

### ISSUE THREAD

**Issue by mclbrunner** [centrify/powershell-sdk#10]
When I try to pull the domain object using the "get-vault" domain, I get the error: "Query has failed: function lower() does not exist". More details on the attached file. My tenant ID is ABB0912

Thanks!

Marcelo Brunner

![image001](https://user-images.githubusercontent.com/79327780/108537826-afd2de00-72a3-11eb-9ab6-157c392e72df.png)

**Comment by badrogh** [comment]
Fixed on Redrock query level. Collation were different depending on the tenant being hosted on Azure or AWS, now unified.

**Comment by badrogh** [comment]
Further fix added by re-writing the Redrock query management.
