### ISSUE TITLE
Script error in Set-VaultSecret when updating Name and Description

### ISSUE THREAD

**Issue by ijromeo** [centrify/powershell-sdk#12]
Hi! When you make a Set-VaultSecret -VaultSecret (Get-VaultSecret -Name "Test") -Name "Name" -Description "Description" to update the Name and Description of a Secret, only the Name is updated and takes the value of the Description parameter.

Here is the error on Set-VaultSecret.ps1:

# Update Name and Description if needed
        if ([System.String]::IsNullOrEmpty($Name))
        {
            # Keep value
            $JsonQuery.SecretName 	= $VaultSecret.SecretName
        }
        else
        {
            # Update value
            $JsonQuery.SecretName 	= $Name
        }

        if ([System.String]::IsNullOrEmpty($Description))
        {
            # Keep value
            $JsonQuery.Description 	= $VaultSecret.Description
        }
        else
        {
            # Update value
               $JsonQuery.SecretName 	= $Description HERE IS THE ERROR ON LINE 121. IT SHOULD BE:
               $JsonQuery.Description = $Description
        }

Greetings!

**Comment by badrogh** [comment]
Fixed and merged in master branch, will be added to next release. Thanks Ignacio.
