### ISSUE TITLE
bug in Centrify.Platform.PowerShell/Lib/New-VaultAlternateAccount.ps1

### ISSUE THREAD

**Issue by fleavis-centrify** [centrify/powershell-sdk#9]
line 71 in the file Centrify.Platform.PowerShell/Lib/New-VaultAlternateAccount.ps1 reads:
$VaultAccount = Get-VaultAccount -Domain (Get-VaultDomain -Name $AccountDomain) -User $AccountName

this should read:
$VaultAccount = Get-VaultAccount -VaultDomain (Get-VaultDomain -Name $AccountDomain) -User $AccountName

**Comment by badrogh** [comment]
Fixed.
